CREATE TABLE LOG_SOURCE
(
  id INT PRIMARY KEY NOT NULL,
  APP_NAME VARCHAR(50) NOT NULL,
  SELECTED VARCHAR(10)
);
CREATE SEQUENCE LOG_SOURCE_SEQ
minvalue 1
maxvalue 9999999999
start with 1
increment by 1;